package:
  name: wera2netcdf
  version: "1.0.0"

source:
    path: ../

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest
    - pandas
    - netcdf4
    - pygc
    - pytz
    - python-dateutil

  run:
    - python
    - pytest
    - pandas
    - netcdf4
    - pygc
    - pytz
    - python-dateutil

test:
  imports:
    - wera2netcdf
    - wera2netcdf.tests

  requires:
    - pytest

about:
  home: https://github.com/axiom-data-science/wera2netcdf
  license: MIT License
  summary: 'A utility to convert WERA total ASCII files into CF NetCDF files.'
